/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.assetmanagement.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.rivetlogic.assetmanagement.model.AssetMessage;
import com.rivetlogic.assetmanagement.service.AssetMessageLocalService;
import com.rivetlogic.assetmanagement.service.persistence.AssetCategoryPersistence;
import com.rivetlogic.assetmanagement.service.persistence.AssetLocationPersistence;
import com.rivetlogic.assetmanagement.service.persistence.AssetMessagePersistence;
import com.rivetlogic.assetmanagement.service.persistence.AssetPersistence;
import com.rivetlogic.assetmanagement.service.persistence.AssetRequestPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the asset message local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.rivetlogic.assetmanagement.service.impl.AssetMessageLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.rivetlogic.assetmanagement.service.impl.AssetMessageLocalServiceImpl
 * @see com.rivetlogic.assetmanagement.service.AssetMessageLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class AssetMessageLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements AssetMessageLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.rivetlogic.assetmanagement.service.AssetMessageLocalServiceUtil} to access the asset message local service.
	 */

	/**
	 * Adds the asset message to the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetMessage the asset message
	 * @return the asset message that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetMessage addAssetMessage(AssetMessage assetMessage) {
		assetMessage.setNew(true);

		return assetMessagePersistence.update(assetMessage);
	}

	/**
	 * Creates a new asset message with the primary key. Does not add the asset message to the database.
	 *
	 * @param assetMessageId the primary key for the new asset message
	 * @return the new asset message
	 */
	@Override
	public AssetMessage createAssetMessage(long assetMessageId) {
		return assetMessagePersistence.create(assetMessageId);
	}

	/**
	 * Deletes the asset message with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetMessageId the primary key of the asset message
	 * @return the asset message that was removed
	 * @throws PortalException if a asset message with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetMessage deleteAssetMessage(long assetMessageId)
		throws PortalException {
		return assetMessagePersistence.remove(assetMessageId);
	}

	/**
	 * Deletes the asset message from the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetMessage the asset message
	 * @return the asset message that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetMessage deleteAssetMessage(AssetMessage assetMessage) {
		return assetMessagePersistence.remove(assetMessage);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(AssetMessage.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return assetMessagePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rivetlogic.assetmanagement.model.impl.AssetMessageModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return assetMessagePersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rivetlogic.assetmanagement.model.impl.AssetMessageModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return assetMessagePersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return assetMessagePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return assetMessagePersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public AssetMessage fetchAssetMessage(long assetMessageId) {
		return assetMessagePersistence.fetchByPrimaryKey(assetMessageId);
	}

	/**
	 * Returns the asset message matching the UUID and group.
	 *
	 * @param uuid the asset message's UUID
	 * @param groupId the primary key of the group
	 * @return the matching asset message, or <code>null</code> if a matching asset message could not be found
	 */
	@Override
	public AssetMessage fetchAssetMessageByUuidAndGroupId(String uuid,
		long groupId) {
		return assetMessagePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the asset message with the primary key.
	 *
	 * @param assetMessageId the primary key of the asset message
	 * @return the asset message
	 * @throws PortalException if a asset message with the primary key could not be found
	 */
	@Override
	public AssetMessage getAssetMessage(long assetMessageId)
		throws PortalException {
		return assetMessagePersistence.findByPrimaryKey(assetMessageId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(assetMessageLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetMessage.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("assetMessageId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(assetMessageLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AssetMessage.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetMessageId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(assetMessageLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetMessage.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("assetMessageId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return assetMessageLocalService.deleteAssetMessage((AssetMessage)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return assetMessagePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the asset messages matching the UUID and company.
	 *
	 * @param uuid the UUID of the asset messages
	 * @param companyId the primary key of the company
	 * @return the matching asset messages, or an empty list if no matches were found
	 */
	@Override
	public List<AssetMessage> getAssetMessagesByUuidAndCompanyId(String uuid,
		long companyId) {
		return assetMessagePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of asset messages matching the UUID and company.
	 *
	 * @param uuid the UUID of the asset messages
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of asset messages
	 * @param end the upper bound of the range of asset messages (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching asset messages, or an empty list if no matches were found
	 */
	@Override
	public List<AssetMessage> getAssetMessagesByUuidAndCompanyId(String uuid,
		long companyId, int start, int end,
		OrderByComparator<AssetMessage> orderByComparator) {
		return assetMessagePersistence.findByUuid_C(uuid, companyId, start,
			end, orderByComparator);
	}

	/**
	 * Returns the asset message matching the UUID and group.
	 *
	 * @param uuid the asset message's UUID
	 * @param groupId the primary key of the group
	 * @return the matching asset message
	 * @throws PortalException if a matching asset message could not be found
	 */
	@Override
	public AssetMessage getAssetMessageByUuidAndGroupId(String uuid,
		long groupId) throws PortalException {
		return assetMessagePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the asset messages.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rivetlogic.assetmanagement.model.impl.AssetMessageModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of asset messages
	 * @param end the upper bound of the range of asset messages (not inclusive)
	 * @return the range of asset messages
	 */
	@Override
	public List<AssetMessage> getAssetMessages(int start, int end) {
		return assetMessagePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of asset messages.
	 *
	 * @return the number of asset messages
	 */
	@Override
	public int getAssetMessagesCount() {
		return assetMessagePersistence.countAll();
	}

	/**
	 * Updates the asset message in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param assetMessage the asset message
	 * @return the asset message that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetMessage updateAssetMessage(AssetMessage assetMessage) {
		return assetMessagePersistence.update(assetMessage);
	}

	/**
	 * Returns the asset local service.
	 *
	 * @return the asset local service
	 */
	public com.rivetlogic.assetmanagement.service.AssetLocalService getAssetLocalService() {
		return assetLocalService;
	}

	/**
	 * Sets the asset local service.
	 *
	 * @param assetLocalService the asset local service
	 */
	public void setAssetLocalService(
		com.rivetlogic.assetmanagement.service.AssetLocalService assetLocalService) {
		this.assetLocalService = assetLocalService;
	}

	/**
	 * Returns the asset persistence.
	 *
	 * @return the asset persistence
	 */
	public AssetPersistence getAssetPersistence() {
		return assetPersistence;
	}

	/**
	 * Sets the asset persistence.
	 *
	 * @param assetPersistence the asset persistence
	 */
	public void setAssetPersistence(AssetPersistence assetPersistence) {
		this.assetPersistence = assetPersistence;
	}

	/**
	 * Returns the asset category local service.
	 *
	 * @return the asset category local service
	 */
	public com.rivetlogic.assetmanagement.service.AssetCategoryLocalService getAssetCategoryLocalService() {
		return assetCategoryLocalService;
	}

	/**
	 * Sets the asset category local service.
	 *
	 * @param assetCategoryLocalService the asset category local service
	 */
	public void setAssetCategoryLocalService(
		com.rivetlogic.assetmanagement.service.AssetCategoryLocalService assetCategoryLocalService) {
		this.assetCategoryLocalService = assetCategoryLocalService;
	}

	/**
	 * Returns the asset category persistence.
	 *
	 * @return the asset category persistence
	 */
	public AssetCategoryPersistence getAssetCategoryPersistence() {
		return assetCategoryPersistence;
	}

	/**
	 * Sets the asset category persistence.
	 *
	 * @param assetCategoryPersistence the asset category persistence
	 */
	public void setAssetCategoryPersistence(
		AssetCategoryPersistence assetCategoryPersistence) {
		this.assetCategoryPersistence = assetCategoryPersistence;
	}

	/**
	 * Returns the asset location local service.
	 *
	 * @return the asset location local service
	 */
	public com.rivetlogic.assetmanagement.service.AssetLocationLocalService getAssetLocationLocalService() {
		return assetLocationLocalService;
	}

	/**
	 * Sets the asset location local service.
	 *
	 * @param assetLocationLocalService the asset location local service
	 */
	public void setAssetLocationLocalService(
		com.rivetlogic.assetmanagement.service.AssetLocationLocalService assetLocationLocalService) {
		this.assetLocationLocalService = assetLocationLocalService;
	}

	/**
	 * Returns the asset location persistence.
	 *
	 * @return the asset location persistence
	 */
	public AssetLocationPersistence getAssetLocationPersistence() {
		return assetLocationPersistence;
	}

	/**
	 * Sets the asset location persistence.
	 *
	 * @param assetLocationPersistence the asset location persistence
	 */
	public void setAssetLocationPersistence(
		AssetLocationPersistence assetLocationPersistence) {
		this.assetLocationPersistence = assetLocationPersistence;
	}

	/**
	 * Returns the asset message local service.
	 *
	 * @return the asset message local service
	 */
	public AssetMessageLocalService getAssetMessageLocalService() {
		return assetMessageLocalService;
	}

	/**
	 * Sets the asset message local service.
	 *
	 * @param assetMessageLocalService the asset message local service
	 */
	public void setAssetMessageLocalService(
		AssetMessageLocalService assetMessageLocalService) {
		this.assetMessageLocalService = assetMessageLocalService;
	}

	/**
	 * Returns the asset message persistence.
	 *
	 * @return the asset message persistence
	 */
	public AssetMessagePersistence getAssetMessagePersistence() {
		return assetMessagePersistence;
	}

	/**
	 * Sets the asset message persistence.
	 *
	 * @param assetMessagePersistence the asset message persistence
	 */
	public void setAssetMessagePersistence(
		AssetMessagePersistence assetMessagePersistence) {
		this.assetMessagePersistence = assetMessagePersistence;
	}

	/**
	 * Returns the asset request local service.
	 *
	 * @return the asset request local service
	 */
	public com.rivetlogic.assetmanagement.service.AssetRequestLocalService getAssetRequestLocalService() {
		return assetRequestLocalService;
	}

	/**
	 * Sets the asset request local service.
	 *
	 * @param assetRequestLocalService the asset request local service
	 */
	public void setAssetRequestLocalService(
		com.rivetlogic.assetmanagement.service.AssetRequestLocalService assetRequestLocalService) {
		this.assetRequestLocalService = assetRequestLocalService;
	}

	/**
	 * Returns the asset request persistence.
	 *
	 * @return the asset request persistence
	 */
	public AssetRequestPersistence getAssetRequestPersistence() {
		return assetRequestPersistence;
	}

	/**
	 * Sets the asset request persistence.
	 *
	 * @param assetRequestPersistence the asset request persistence
	 */
	public void setAssetRequestPersistence(
		AssetRequestPersistence assetRequestPersistence) {
		this.assetRequestPersistence = assetRequestPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.rivetlogic.assetmanagement.model.AssetMessage",
			assetMessageLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.rivetlogic.assetmanagement.model.AssetMessage");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetMessageLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AssetMessage.class;
	}

	protected String getModelClassName() {
		return AssetMessage.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = assetMessagePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.rivetlogic.assetmanagement.service.AssetLocalService.class)
	protected com.rivetlogic.assetmanagement.service.AssetLocalService assetLocalService;
	@BeanReference(type = AssetPersistence.class)
	protected AssetPersistence assetPersistence;
	@BeanReference(type = com.rivetlogic.assetmanagement.service.AssetCategoryLocalService.class)
	protected com.rivetlogic.assetmanagement.service.AssetCategoryLocalService assetCategoryLocalService;
	@BeanReference(type = AssetCategoryPersistence.class)
	protected AssetCategoryPersistence assetCategoryPersistence;
	@BeanReference(type = com.rivetlogic.assetmanagement.service.AssetLocationLocalService.class)
	protected com.rivetlogic.assetmanagement.service.AssetLocationLocalService assetLocationLocalService;
	@BeanReference(type = AssetLocationPersistence.class)
	protected AssetLocationPersistence assetLocationPersistence;
	@BeanReference(type = AssetMessageLocalService.class)
	protected AssetMessageLocalService assetMessageLocalService;
	@BeanReference(type = AssetMessagePersistence.class)
	protected AssetMessagePersistence assetMessagePersistence;
	@BeanReference(type = com.rivetlogic.assetmanagement.service.AssetRequestLocalService.class)
	protected com.rivetlogic.assetmanagement.service.AssetRequestLocalService assetRequestLocalService;
	@BeanReference(type = AssetRequestPersistence.class)
	protected AssetRequestPersistence assetRequestPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}