/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.assetmanagement.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.dao.orm.Session;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.rivetlogic.assetmanagement.model.Asset;
import com.rivetlogic.assetmanagement.model.AssetPhotoBlobModel;
import com.rivetlogic.assetmanagement.service.AssetLocalService;
import com.rivetlogic.assetmanagement.service.persistence.AssetCategoryPersistence;
import com.rivetlogic.assetmanagement.service.persistence.AssetLocationPersistence;
import com.rivetlogic.assetmanagement.service.persistence.AssetMessagePersistence;
import com.rivetlogic.assetmanagement.service.persistence.AssetPersistence;
import com.rivetlogic.assetmanagement.service.persistence.AssetRequestPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the asset local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.rivetlogic.assetmanagement.service.impl.AssetLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.rivetlogic.assetmanagement.service.impl.AssetLocalServiceImpl
 * @see com.rivetlogic.assetmanagement.service.AssetLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class AssetLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements AssetLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.rivetlogic.assetmanagement.service.AssetLocalServiceUtil} to access the asset local service.
	 */

	/**
	 * Adds the asset to the database. Also notifies the appropriate model listeners.
	 *
	 * @param asset the asset
	 * @return the asset that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Asset addAsset(Asset asset) {
		asset.setNew(true);

		return assetPersistence.update(asset);
	}

	/**
	 * Creates a new asset with the primary key. Does not add the asset to the database.
	 *
	 * @param assetId the primary key for the new asset
	 * @return the new asset
	 */
	@Override
	public Asset createAsset(long assetId) {
		return assetPersistence.create(assetId);
	}

	/**
	 * Deletes the asset with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetId the primary key of the asset
	 * @return the asset that was removed
	 * @throws PortalException if a asset with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Asset deleteAsset(long assetId) throws PortalException {
		return assetPersistence.remove(assetId);
	}

	/**
	 * Deletes the asset from the database. Also notifies the appropriate model listeners.
	 *
	 * @param asset the asset
	 * @return the asset that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Asset deleteAsset(Asset asset) {
		return assetPersistence.remove(asset);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Asset.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return assetPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rivetlogic.assetmanagement.model.impl.AssetModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return assetPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rivetlogic.assetmanagement.model.impl.AssetModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return assetPersistence.findWithDynamicQuery(dynamicQuery, start, end,
			orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return assetPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return assetPersistence.countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public Asset fetchAsset(long assetId) {
		return assetPersistence.fetchByPrimaryKey(assetId);
	}

	/**
	 * Returns the asset matching the UUID and group.
	 *
	 * @param uuid the asset's UUID
	 * @param groupId the primary key of the group
	 * @return the matching asset, or <code>null</code> if a matching asset could not be found
	 */
	@Override
	public Asset fetchAssetByUuidAndGroupId(String uuid, long groupId) {
		return assetPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the asset with the primary key.
	 *
	 * @param assetId the primary key of the asset
	 * @return the asset
	 * @throws PortalException if a asset with the primary key could not be found
	 */
	@Override
	public Asset getAsset(long assetId) throws PortalException {
		return assetPersistence.findByPrimaryKey(assetId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(assetLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Asset.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("assetId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(assetLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Asset.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("assetId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(assetLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Asset.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("assetId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {
		final ExportActionableDynamicQuery exportActionableDynamicQuery = new ExportActionableDynamicQuery() {
				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary = portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(stagedModelType,
						modelAdditionCount);

					long modelDeletionCount = ExportImportHelperUtil.getModelDeletionCount(portletDataContext,
							stagedModelType);

					manifestSummary.addModelDeletionCount(stagedModelType,
						modelDeletionCount);

					return modelAdditionCount;
				}
			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(new ActionableDynamicQuery.AddCriteriaMethod() {
				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(dynamicQuery,
						"modifiedDate");
				}
			});

		exportActionableDynamicQuery.setCompanyId(portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(new ActionableDynamicQuery.PerformActionMethod<Asset>() {
				@Override
				public void performAction(Asset asset)
					throws PortalException {
					StagedModelDataHandlerUtil.exportStagedModel(portletDataContext,
						asset);
				}
			});
		exportActionableDynamicQuery.setStagedModelType(new StagedModelType(
				PortalUtil.getClassNameId(Asset.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return assetLocalService.deleteAsset((Asset)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return assetPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the assets matching the UUID and company.
	 *
	 * @param uuid the UUID of the assets
	 * @param companyId the primary key of the company
	 * @return the matching assets, or an empty list if no matches were found
	 */
	@Override
	public List<Asset> getAssetsByUuidAndCompanyId(String uuid, long companyId) {
		return assetPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of assets matching the UUID and company.
	 *
	 * @param uuid the UUID of the assets
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of assets
	 * @param end the upper bound of the range of assets (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching assets, or an empty list if no matches were found
	 */
	@Override
	public List<Asset> getAssetsByUuidAndCompanyId(String uuid, long companyId,
		int start, int end, OrderByComparator<Asset> orderByComparator) {
		return assetPersistence.findByUuid_C(uuid, companyId, start, end,
			orderByComparator);
	}

	/**
	 * Returns the asset matching the UUID and group.
	 *
	 * @param uuid the asset's UUID
	 * @param groupId the primary key of the group
	 * @return the matching asset
	 * @throws PortalException if a matching asset could not be found
	 */
	@Override
	public Asset getAssetByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {
		return assetPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the assets.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rivetlogic.assetmanagement.model.impl.AssetModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of assets
	 * @param end the upper bound of the range of assets (not inclusive)
	 * @return the range of assets
	 */
	@Override
	public List<Asset> getAssets(int start, int end) {
		return assetPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of assets.
	 *
	 * @return the number of assets
	 */
	@Override
	public int getAssetsCount() {
		return assetPersistence.countAll();
	}

	/**
	 * Updates the asset in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param asset the asset
	 * @return the asset that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Asset updateAsset(Asset asset) {
		return assetPersistence.update(asset);
	}

	@Override
	public AssetPhotoBlobModel getPhotoBlobModel(Serializable primaryKey) {
		Session session = null;

		try {
			session = assetPersistence.openSession();

			return (AssetPhotoBlobModel)session.get(AssetPhotoBlobModel.class,
				primaryKey);
		}
		catch (Exception e) {
			throw assetPersistence.processException(e);
		}
		finally {
			assetPersistence.closeSession(session);
		}
	}

	/**
	 * Returns the asset local service.
	 *
	 * @return the asset local service
	 */
	public AssetLocalService getAssetLocalService() {
		return assetLocalService;
	}

	/**
	 * Sets the asset local service.
	 *
	 * @param assetLocalService the asset local service
	 */
	public void setAssetLocalService(AssetLocalService assetLocalService) {
		this.assetLocalService = assetLocalService;
	}

	/**
	 * Returns the asset persistence.
	 *
	 * @return the asset persistence
	 */
	public AssetPersistence getAssetPersistence() {
		return assetPersistence;
	}

	/**
	 * Sets the asset persistence.
	 *
	 * @param assetPersistence the asset persistence
	 */
	public void setAssetPersistence(AssetPersistence assetPersistence) {
		this.assetPersistence = assetPersistence;
	}

	/**
	 * Returns the asset category local service.
	 *
	 * @return the asset category local service
	 */
	public com.rivetlogic.assetmanagement.service.AssetCategoryLocalService getAssetCategoryLocalService() {
		return assetCategoryLocalService;
	}

	/**
	 * Sets the asset category local service.
	 *
	 * @param assetCategoryLocalService the asset category local service
	 */
	public void setAssetCategoryLocalService(
		com.rivetlogic.assetmanagement.service.AssetCategoryLocalService assetCategoryLocalService) {
		this.assetCategoryLocalService = assetCategoryLocalService;
	}

	/**
	 * Returns the asset category persistence.
	 *
	 * @return the asset category persistence
	 */
	public AssetCategoryPersistence getAssetCategoryPersistence() {
		return assetCategoryPersistence;
	}

	/**
	 * Sets the asset category persistence.
	 *
	 * @param assetCategoryPersistence the asset category persistence
	 */
	public void setAssetCategoryPersistence(
		AssetCategoryPersistence assetCategoryPersistence) {
		this.assetCategoryPersistence = assetCategoryPersistence;
	}

	/**
	 * Returns the asset location local service.
	 *
	 * @return the asset location local service
	 */
	public com.rivetlogic.assetmanagement.service.AssetLocationLocalService getAssetLocationLocalService() {
		return assetLocationLocalService;
	}

	/**
	 * Sets the asset location local service.
	 *
	 * @param assetLocationLocalService the asset location local service
	 */
	public void setAssetLocationLocalService(
		com.rivetlogic.assetmanagement.service.AssetLocationLocalService assetLocationLocalService) {
		this.assetLocationLocalService = assetLocationLocalService;
	}

	/**
	 * Returns the asset location persistence.
	 *
	 * @return the asset location persistence
	 */
	public AssetLocationPersistence getAssetLocationPersistence() {
		return assetLocationPersistence;
	}

	/**
	 * Sets the asset location persistence.
	 *
	 * @param assetLocationPersistence the asset location persistence
	 */
	public void setAssetLocationPersistence(
		AssetLocationPersistence assetLocationPersistence) {
		this.assetLocationPersistence = assetLocationPersistence;
	}

	/**
	 * Returns the asset message local service.
	 *
	 * @return the asset message local service
	 */
	public com.rivetlogic.assetmanagement.service.AssetMessageLocalService getAssetMessageLocalService() {
		return assetMessageLocalService;
	}

	/**
	 * Sets the asset message local service.
	 *
	 * @param assetMessageLocalService the asset message local service
	 */
	public void setAssetMessageLocalService(
		com.rivetlogic.assetmanagement.service.AssetMessageLocalService assetMessageLocalService) {
		this.assetMessageLocalService = assetMessageLocalService;
	}

	/**
	 * Returns the asset message persistence.
	 *
	 * @return the asset message persistence
	 */
	public AssetMessagePersistence getAssetMessagePersistence() {
		return assetMessagePersistence;
	}

	/**
	 * Sets the asset message persistence.
	 *
	 * @param assetMessagePersistence the asset message persistence
	 */
	public void setAssetMessagePersistence(
		AssetMessagePersistence assetMessagePersistence) {
		this.assetMessagePersistence = assetMessagePersistence;
	}

	/**
	 * Returns the asset request local service.
	 *
	 * @return the asset request local service
	 */
	public com.rivetlogic.assetmanagement.service.AssetRequestLocalService getAssetRequestLocalService() {
		return assetRequestLocalService;
	}

	/**
	 * Sets the asset request local service.
	 *
	 * @param assetRequestLocalService the asset request local service
	 */
	public void setAssetRequestLocalService(
		com.rivetlogic.assetmanagement.service.AssetRequestLocalService assetRequestLocalService) {
		this.assetRequestLocalService = assetRequestLocalService;
	}

	/**
	 * Returns the asset request persistence.
	 *
	 * @return the asset request persistence
	 */
	public AssetRequestPersistence getAssetRequestPersistence() {
		return assetRequestPersistence;
	}

	/**
	 * Sets the asset request persistence.
	 *
	 * @param assetRequestPersistence the asset request persistence
	 */
	public void setAssetRequestPersistence(
		AssetRequestPersistence assetRequestPersistence) {
		this.assetRequestPersistence = assetRequestPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.rivetlogic.assetmanagement.model.Asset",
			assetLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.rivetlogic.assetmanagement.model.Asset");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Asset.class;
	}

	protected String getModelClassName() {
		return Asset.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = assetPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = AssetLocalService.class)
	protected AssetLocalService assetLocalService;
	@BeanReference(type = AssetPersistence.class)
	protected AssetPersistence assetPersistence;
	@BeanReference(type = com.rivetlogic.assetmanagement.service.AssetCategoryLocalService.class)
	protected com.rivetlogic.assetmanagement.service.AssetCategoryLocalService assetCategoryLocalService;
	@BeanReference(type = AssetCategoryPersistence.class)
	protected AssetCategoryPersistence assetCategoryPersistence;
	@BeanReference(type = com.rivetlogic.assetmanagement.service.AssetLocationLocalService.class)
	protected com.rivetlogic.assetmanagement.service.AssetLocationLocalService assetLocationLocalService;
	@BeanReference(type = AssetLocationPersistence.class)
	protected AssetLocationPersistence assetLocationPersistence;
	@BeanReference(type = com.rivetlogic.assetmanagement.service.AssetMessageLocalService.class)
	protected com.rivetlogic.assetmanagement.service.AssetMessageLocalService assetMessageLocalService;
	@BeanReference(type = AssetMessagePersistence.class)
	protected AssetMessagePersistence assetMessagePersistence;
	@BeanReference(type = com.rivetlogic.assetmanagement.service.AssetRequestLocalService.class)
	protected com.rivetlogic.assetmanagement.service.AssetRequestLocalService assetRequestLocalService;
	@BeanReference(type = AssetRequestPersistence.class)
	protected AssetRequestPersistence assetRequestPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}