/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.assetmanagement.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AssetMessage service. Represents a row in the &quot;rivetlogic_AssetMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.assetmanagement.model.impl.AssetMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.assetmanagement.model.impl.AssetMessageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetMessage
 * @see com.rivetlogic.assetmanagement.model.impl.AssetMessageImpl
 * @see com.rivetlogic.assetmanagement.model.impl.AssetMessageModelImpl
 * @generated
 */
@ProviderType
public interface AssetMessageModel extends BaseModel<AssetMessage>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset message model instance should use the {@link AssetMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this asset message.
	 *
	 * @return the primary key of this asset message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset message.
	 *
	 * @param primaryKey the primary key of this asset message
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this asset message.
	 *
	 * @return the uuid of this asset message
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this asset message.
	 *
	 * @param uuid the uuid of this asset message
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the asset message ID of this asset message.
	 *
	 * @return the asset message ID of this asset message
	 */
	public long getAssetMessageId();

	/**
	 * Sets the asset message ID of this asset message.
	 *
	 * @param assetMessageId the asset message ID of this asset message
	 */
	public void setAssetMessageId(long assetMessageId);

	/**
	 * Returns the group ID of this asset message.
	 *
	 * @return the group ID of this asset message
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this asset message.
	 *
	 * @param groupId the group ID of this asset message
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this asset message.
	 *
	 * @return the company ID of this asset message
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this asset message.
	 *
	 * @param companyId the company ID of this asset message
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this asset message.
	 *
	 * @return the create date of this asset message
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this asset message.
	 *
	 * @param createDate the create date of this asset message
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the asset ID of this asset message.
	 *
	 * @return the asset ID of this asset message
	 */
	public long getAssetId();

	/**
	 * Sets the asset ID of this asset message.
	 *
	 * @param assetId the asset ID of this asset message
	 */
	public void setAssetId(long assetId);

	/**
	 * Returns the from user ID of this asset message.
	 *
	 * @return the from user ID of this asset message
	 */
	public long getFromUserId();

	/**
	 * Sets the from user ID of this asset message.
	 *
	 * @param fromUserId the from user ID of this asset message
	 */
	public void setFromUserId(long fromUserId);

	/**
	 * Returns the from user uuid of this asset message.
	 *
	 * @return the from user uuid of this asset message
	 */
	public String getFromUserUuid();

	/**
	 * Sets the from user uuid of this asset message.
	 *
	 * @param fromUserUuid the from user uuid of this asset message
	 */
	public void setFromUserUuid(String fromUserUuid);

	/**
	 * Returns the to user ID of this asset message.
	 *
	 * @return the to user ID of this asset message
	 */
	public long getToUserId();

	/**
	 * Sets the to user ID of this asset message.
	 *
	 * @param toUserId the to user ID of this asset message
	 */
	public void setToUserId(long toUserId);

	/**
	 * Returns the to user uuid of this asset message.
	 *
	 * @return the to user uuid of this asset message
	 */
	public String getToUserUuid();

	/**
	 * Sets the to user uuid of this asset message.
	 *
	 * @param toUserUuid the to user uuid of this asset message
	 */
	public void setToUserUuid(String toUserUuid);

	/**
	 * Returns the message of this asset message.
	 *
	 * @return the message of this asset message
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this asset message.
	 *
	 * @param message the message of this asset message
	 */
	public void setMessage(String message);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AssetMessage assetMessage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AssetMessage> toCacheModel();

	@Override
	public AssetMessage toEscapedModel();

	@Override
	public AssetMessage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}